---
language: node_js
sudo: false
node_js:
  - "6"

install: npm install

before_script:
  - npm install -g grunt-cli

script: grunt lint

cache:
  directories:
  - node_modules

branches:
  only:
    - master
